# Generated by Django 6.0.6 on 2026-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='items_name_dd4454_idx'), models.Index(fields=['hsn_sac_code'], name='items_hsn_sac_7b2f56_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='item_quantity_gte_zero'), models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='item_rate_gte_zero')],
            },
        ),
    ]
