# Generated by Django 6.0.6 on 2026-06-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'combos',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='combos_name_f271ab_idx'), models.Index(fields=['created_at'], name='combos_created_cc1755_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComboBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='combo.combo')),
            ],
            options={
                'db_table': 'combo_barcodes',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['barcode'], name='combo_barco_barcode_ae4411_idx'), models.Index(fields=['status'], name='combo_barco_status_3a0ece_idx'), models.Index(fields=['combo'], name='combo_barco_combo_i_a9af13_idx'), models.Index(fields=['combo', 'status'], name='combo_barco_combo_i_c93451_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='combo.combo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo_items', to='items.item')),
            ],
            options={
                'db_table': 'combo_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['combo'], name='combo_items_combo_i_f11176_idx'), models.Index(fields=['item'], name='combo_items_item_id_ff9d16_idx'), models.Index(fields=['combo', 'item'], name='combo_items_combo_i_71b466_idx')],
                'constraints': [models.UniqueConstraint(fields=('combo', 'item'), name='unique_combo_item')],
            },
        ),
    ]
