# Generated by Django 6.0.6 on 2026-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['name'], name='clients_name_0bc5f0_idx'), models.Index(fields=['phone'], name='clients_phone_459745_idx'), models.Index(fields=['email'], name='clients_email_4c8bec_idx'), models.Index(fields=['status'], name='clients_status_98ee60_idx'), models.Index(fields=['created_at'], name='clients_created_4c189f_idx')],
            },
        ),
    ]
