# Generated by Django 6.0.6 on 2026-06-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('combo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='client.client')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='booking.booking')),
                ('combo_barcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='combo.combobarcode')),
            ],
            options={
                'db_table': 'booking_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BookingItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('reference_id', models.PositiveBigIntegerField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_item_logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['reference_id'], name='booking_ite_referen_899e3a_idx'), models.Index(fields=['action'], name='booking_ite_action_b9b9cf_idx'), models.Index(fields=['created_at'], name='booking_ite_created_63eec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('reference_id', models.PositiveBigIntegerField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['reference_id'], name='booking_log_referen_3c77ea_idx'), models.Index(fields=['action'], name='booking_log_action_8b4c7f_idx'), models.Index(fields=['created_at'], name='booking_log_created_bd53e5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='bookings_client__70b0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['booking'], name='booking_ite_booking_b3bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['combo_barcode'], name='booking_ite_combo_b_b5fdc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('combo_barcode',), name='unique_booked_combo_barcode'),
        ),
    ]
