# Generated by Django 6.0.6 on 2026-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='scanned_pairs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
