# Generated by Django 6.0.6 on 2026-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('items', 'items'), ('combo', 'combo'), ('combo_items', 'combo_items'), ('booking', 'booking'), ('booking_items', 'booking_items'), ('client', 'client'), ('combo_barcode', 'combo_barcode')], db_index=True, max_length=50)),
                ('record_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='PK of the affected row in the source table', null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('old_data', models.JSONField(blank=True, help_text='Row snapshot BEFORE the change', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Row snapshot AFTER the change', null=True)),
                ('changed_by', models.CharField(blank=True, help_text='Username or user ID who made the change', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['module', 'action'], name='logs_module_43690d_idx'), models.Index(fields=['module', 'created_at'], name='logs_module_089bd8_idx'), models.Index(fields=['record_id'], name='logs_record__c28c15_idx')],
            },
        ),
    ]
